=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_nested.xsd
<?xml version="1.0"?>
<!--Generated 8/19/2002 6:06:09 PM by EditML Pro, Version 2.5-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="nameType">
		<xsd:sequence>
			<xsd:element name="first_name" type="xsd:string"/>
			<xsd:element name="middle_name" type="xsd:string"/>
			<xsd:element name="last_name" type="xsd:string"/>
			<xsd:element name="nick_name" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="addressType">
		<xsd:sequence>
			<xsd:element name="street_address" type="xsd:string"/>
			<xsd:element name="street_address_detail" type="xsd:string"/>
			<xsd:element name="city" type="xsd:string"/>
			<xsd:element name="state" type="xsd:string"/>
			<xsd:element name="zipcode" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="contactType">
		<xsd:sequence>
			<xsd:element name="home_phone" type="xsd:string"/>
			<xsd:element name="work_phone" type="xsd:string"/>
			<xsd:element name="cell_phone" type="xsd:string"/>
			<xsd:element name="fax_number" type="xsd:string"/>
			<xsd:element name="email_address" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="commentsType">
		<xsd:sequence>
			<xsd:element name="misc_comments" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="recordType">
		<xsd:sequence>
			<xsd:element name="name" type="nameType"/>
			<xsd:element name="address" type="addressType"/>
			<xsd:element name="contact" type="contactType"/>
			<xsd:element name="comments" type="commentsType"/>
		</xsd:sequence>
		<xsd:attribute name="ID" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="address_book_nestedType">
		<xsd:sequence>
			<xsd:element name="record" type="recordType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="address_book_nested" type="address_book_nestedType"/>
</xsd:schema>

=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_nested_xsd.xml
<?xml version="1.0"?>
<!--address book using nested elements-->
<address_book_nested xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="address_book_nested.xsd">
	<record ID="1">
		<name>
			<first_name>first name</first_name>
			<middle_name>middle name</middle_name>
			<last_name>last name</last_name>
			<nick_name>nick name</nick_name>
		</name>
		<address>
			<street_address>street address goes here</street_address>
			<street_address_detail>apartment number goes here</street_address_detail>
			<city>city goes here</city>
			<state>state goes here</state>
			<zipcode>zipcode goes here</zipcode>
		</address>
		<contact>
			<home_phone>home phone goes here</home_phone>
			<work_phone>work phone goes here</work_phone>
			<cell_phone>cell phone goes here</cell_phone>
			<fax_number>fax number goes here</fax_number>
			<email_address>email address goes here</email_address>
		</contact>
		<comments>
			<misc_comments>comments go here</misc_comments>
		</comments>
	</record>
	<record ID="2">
		<name>
			<first_name>first name</first_name>
			<middle_name>middle name</middle_name>
			<last_name>last name</last_name>
			<nick_name>nick name</nick_name>
		</name>
		<address>
			<street_address>street address goes here</street_address>
			<street_address_detail>apartment number goes here</street_address_detail>
			<city>city goes here</city>
			<state>state goes here</state>
			<zipcode>zipcode goes here</zipcode>
		</address>
		<contact>
			<home_phone>home phone goes here</home_phone>
			<work_phone>work phone goes here</work_phone>
			<cell_phone>cell phone goes here</cell_phone>
			<fax_number>fax number goes here</fax_number>
			<email_address>email address goes here</email_address>
		</contact>
		<comments>
			<misc_comments>comments go here</misc_comments>
		</comments>
	</record>
	<record ID="3">
		<name>
			<first_name>first name</first_name>
			<middle_name>middle name</middle_name>
			<last_name>last name</last_name>
			<nick_name>nick name</nick_name>
		</name>
		<address>
			<street_address>street address goes here</street_address>
			<street_address_detail>apartment number goes here</street_address_detail>
			<city>city goes here</city>
			<state>state goes here</state>
			<zipcode>zipcode goes here</zipcode>
		</address>
		<contact>
			<home_phone>home phone goes here</home_phone>
			<work_phone>work phone goes here</work_phone>
			<cell_phone>cell phone goes here</cell_phone>
			<fax_number>fax number goes here</fax_number>
			<email_address>email address goes here</email_address>
		</contact>
		<comments>
			<misc_comments>comments go here</misc_comments>
		</comments>
	</record>
	<record ID="4">
		<name>
			<first_name>first name</first_name>
			<middle_name>middle name</middle_name>
			<last_name>last name</last_name>
			<nick_name>nick name</nick_name>
		</name>
		<address>
			<street_address>street address goes here</street_address>
			<street_address_detail>apartment number goes here</street_address_detail>
			<city>city goes here</city>
			<state>state goes here</state>
			<zipcode>zipcode goes here</zipcode>
		</address>
		<contact>
			<home_phone>home phone goes here</home_phone>
			<work_phone>work phone goes here</work_phone>
			<cell_phone>cell phone goes here</cell_phone>
			<fax_number>fax number goes here</fax_number>
			<email_address>email address goes here</email_address>
		</contact>
		<comments>
			<misc_comments>comments go here</misc_comments>
		</comments>
	</record>
	<record ID="5">
		<name>
			<first_name>first name</first_name>
			<middle_name>middle name</middle_name>
			<last_name>last name</last_name>
			<nick_name>nick name</nick_name>
		</name>
		<address>
			<street_address>street address goes here</street_address>
			<street_address_detail>apartment number goes here</street_address_detail>
			<city>city goes here</city>
			<state>state goes here</state>
			<zipcode>zipcode goes here</zipcode>
		</address>
		<contact>
			<home_phone>home phone goes here</home_phone>
			<work_phone>work phone goes here</work_phone>
			<cell_phone>cell phone goes here</cell_phone>
			<fax_number>fax number goes here</fax_number>
			<email_address>email address goes here</email_address>
		</contact>
		<comments>
			<misc_comments>comments go here</misc_comments>
		</comments>
	</record>
</address_book_nested>
