=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_mixed.dtd
<!--Generated 8/19/2002 2:35:53 PM by EditML Pro, Version 2.5-->
<!ELEMENT address_book_mixed (record*)>
<!ELEMENT record (name_info,address_info,contact_info,comments)>
<!ATTLIST record ID CDATA #REQUIRED>
<!ELEMENT name_info (name*)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name type CDATA #REQUIRED>
<!ELEMENT address_info (address*)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST address type CDATA #REQUIRED>
<!ELEMENT contact_info (phone*,email)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type CDATA #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email type CDATA #REQUIRED>
<!ELEMENT comments (comment)>
<!ELEMENT comment (#PCDATA)>
<!ATTLIST comment type CDATA #REQUIRED>

=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_mixed_dtd.xml
<?xml version="1.0"?>
<!--address book using mixed elements-->
<!DOCTYPE address_book_mixed SYSTEM "address_book_mixed.dtd">
<address_book_mixed>
	<record ID="1">
		<name_info>
			<name type="first">first name</name>
			<name type="middle">middle name</name>
			<name type="last">last name</name>
			<name type="nick">nick name</name>
		</name_info>
		<address_info>
			<address type="street">street address goes here</address>
			<address type="detail">apartment number goes here</address>
			<address type="city">city goes here</address>
			<address type="state">state goes here</address>
			<address type="zipcode">zipcode goes here</address>
		</address_info>
		<contact_info>
			<phone type="home">home phone goes here</phone>
			<phone type="work">work phone goes here</phone>
			<phone type="cell">cell phone goes here</phone>
			<phone type="fax">fax number goes here</phone>
			<email type="primary">email address goes here</email>
		</contact_info>
		<comments>
			<comment type="misc">comments go here</comment>
		</comments>
	</record>
	<record ID="2">
		<name_info>
			<name type="first">first name</name>
			<name type="middle">middle name</name>
			<name type="last">last name</name>
			<name type="nick">nick name</name>
		</name_info>
		<address_info>
			<address type="street">street address goes here</address>
			<address type="detail">apartment number goes here</address>
			<address type="city">city goes here</address>
			<address type="state">state goes here</address>
			<address type="zipcode">zipcode goes here</address>
		</address_info>
		<contact_info>
			<phone type="home">home phone goes here</phone>
			<phone type="work">work phone goes here</phone>
			<phone type="cell">cell phone goes here</phone>
			<phone type="fax">fax number goes here</phone>
			<email type="primary">email address goes here</email>
		</contact_info>
		<comments>
			<comment type="misc">comments go here</comment>
		</comments>
	</record>
	<record ID="3">
		<name_info>
			<name type="first">first name</name>
			<name type="middle">middle name</name>
			<name type="last">last name</name>
			<name type="nick">nick name</name>
		</name_info>
		<address_info>
			<address type="street">street address goes here</address>
			<address type="detail">apartment number goes here</address>
			<address type="city">city goes here</address>
			<address type="state">state goes here</address>
			<address type="zipcode">zipcode goes here</address>
		</address_info>
		<contact_info>
			<phone type="home">home phone goes here</phone>
			<phone type="work">work phone goes here</phone>
			<phone type="cell">cell phone goes here</phone>
			<phone type="fax">fax number goes here</phone>
			<email type="primary">email address goes here</email>
		</contact_info>
		<comments>
			<comment type="misc">comments go here</comment>
		</comments>
	</record>
	<record ID="4">
		<name_info>
			<name type="first">first name</name>
			<name type="middle">middle name</name>
			<name type="last">last name</name>
			<name type="nick">nick name</name>
		</name_info>
		<address_info>
			<address type="street">street address goes here</address>
			<address type="detail">apartment number goes here</address>
			<address type="city">city goes here</address>
			<address type="state">state goes here</address>
			<address type="zipcode">zipcode goes here</address>
		</address_info>
		<contact_info>
			<phone type="home">home phone goes here</phone>
			<phone type="work">work phone goes here</phone>
			<phone type="cell">cell phone goes here</phone>
			<phone type="fax">fax number goes here</phone>
			<email type="primary">email address goes here</email>
		</contact_info>
		<comments>
			<comment type="misc">comments go here</comment>
		</comments>
	</record>
	<record ID="5">
		<name_info>
			<name type="first">first name</name>
			<name type="middle">middle name</name>
			<name type="last">last name</name>
			<name type="nick">nick name</name>
		</name_info>
		<address_info>
			<address type="street">street address goes here</address>
			<address type="detail">apartment number goes here</address>
			<address type="city">city goes here</address>
			<address type="state">state goes here</address>
			<address type="zipcode">zipcode goes here</address>
		</address_info>
		<contact_info>
			<phone type="home">home phone goes here</phone>
			<phone type="work">work phone goes here</phone>
			<phone type="cell">cell phone goes here</phone>
			<phone type="fax">fax number goes here</phone>
			<email type="primary">email address goes here</email>
		</contact_info>
		<comments>
			<comment type="misc">comments go here</comment>
		</comments>
	</record>
</address_book_mixed>
