=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_empty.xsd
<?xml version="1.0"?>
<!--Generated 6/23/2002 7:33:20 AM by EditML Pro, Version 2.5-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="nameType">
		<xsd:attribute name="first_name" type="xsd:string"/>
		<xsd:attribute name="middle_name" type="xsd:string"/>
		<xsd:attribute name="last_name" type="xsd:string"/>
		<xsd:attribute name="nick_name" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="addressType">
		<xsd:attribute name="street_address" type="xsd:string"/>
		<xsd:attribute name="street_address_detail" type="xsd:string"/>
		<xsd:attribute name="city" type="xsd:string"/>
		<xsd:attribute name="state" type="xsd:string"/>
		<xsd:attribute name="zipcode" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="contactType">
		<xsd:attribute name="home_phone" type="xsd:string"/>
		<xsd:attribute name="work_phone" type="xsd:string"/>
		<xsd:attribute name="cell_phone" type="xsd:string"/>
		<xsd:attribute name="fax_number" type="xsd:string"/>
		<xsd:attribute name="e-mail" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="commentsType">
		<xsd:attribute name="comment" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="recordType">
		<xsd:sequence>
			<xsd:element name="name" type="nameType"/>
			<xsd:element name="address" type="addressType"/>
			<xsd:element name="contact" type="contactType"/>
			<xsd:element name="comments" type="commentsType"/>
		</xsd:sequence>
		<xsd:attribute name="ID" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="address_book_emptyType">
		<xsd:sequence>
			<xsd:element name="record" type="recordType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="address_book_empty" type="address_book_emptyType"/>
</xsd:schema>

=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_empty_xsd.xml
<?xml version="1.0"?>
<!--This is an address_book with empty tags linked to a schema document-->
<address_book_empty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="address_book_empty.xsd">
	<record ID="1">
		<name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick"></name>
		<address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode"></address>
		<contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com"></contact>
		<comments comment="text"></comments>
	</record>
	<record ID="2">
		<name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick"></name>
		<address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode"></address>
		<contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com"></contact>
		<comments comment="text"></comments>
	</record>
	<record ID="3">
		<name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick"></name>
		<address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode"></address>
		<contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com"></contact>
		<comments comment="text"></comments>
	</record>
	<record ID="4">
		<name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick"></name>
		<address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode"></address>
		<contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com"></contact>
		<comments comment="text"></comments>
	</record>
	<record ID="5">
		<name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick"></name>
		<address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode"></address>
		<contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com"></contact>
		<comments comment="text"></comments>
	</record>
</address_book_empty>
