=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_empty.dtd
<!ELEMENT address_book_empty (record*)>
<!ELEMENT record (name,address,contact,comments)>
<!ATTLIST record ID CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name first_name CDATA #REQUIRED>
<!ATTLIST name middle_name CDATA #REQUIRED>
<!ATTLIST name last_name CDATA #REQUIRED>
<!ATTLIST name nick_name CDATA #REQUIRED>
<!ELEMENT address (#PCDATA)>
<!ATTLIST address street_address CDATA #REQUIRED>
<!ATTLIST address street_address_detail CDATA #REQUIRED>
<!ATTLIST address city CDATA #REQUIRED>
<!ATTLIST address state CDATA #REQUIRED>
<!ATTLIST address zipcode CDATA #REQUIRED>
<!ELEMENT contact (#PCDATA)>
<!ATTLIST contact home_phone CDATA #REQUIRED>
<!ATTLIST contact work_phone CDATA #REQUIRED>
<!ATTLIST contact cell_phone CDATA #REQUIRED>
<!ATTLIST contact fax_number CDATA #REQUIRED>
<!ATTLIST contact e-mail CDATA #REQUIRED>
<!ELEMENT comments (#PCDATA)>
<!ATTLIST comments comment CDATA #REQUIRED>

=== gaewebdesign/books/fhda/coin78/Address_Book/address_book_empty_dtd.xml
<?xml version="1.0"?>
<!DOCTYPE address_book_empty SYSTEM "address_book_empty.dtd">
<!-- address book with empty tags linked to address_book_empty.dtd -->

<address_book_empty>
<record ID="1">
    <name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick" />
    <address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode" />
    <contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com" />
    <comments comment="text" />
  </record>
  <record ID="2">
    <name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick" />
    <address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode" />
    <contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com" />
    <comments comment="text" />
  </record>
  <record ID="3">
    <name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick" />
    <address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode" />
    <contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com" />
    <comments comment="text" />
  </record>
  <record ID="4">
    <name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick" />
    <address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode" />
    <contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com" />
    <comments comment="text" />
  </record>
  <record ID="5">
    <name first_name="First" middle_name="Middle" last_name="Last" nick_name="Nick" />
    <address street_address="Street Number" street_address_detail="Street Detail" city="City" state="State" zipcode="Zipcode" />
    <contact home_phone="800-555-1212" work_phone="800-555-1212" cell_phone="800-555-1212" fax_number="800-555-1212" e-mail="user@whatever.com" />
    <comments comment="text" />
  </record>
</address_book_empty>
